spring:
  application:
    name: table-tennisCa

  datasource:
    url: jdbc:h2:tcp://localhost/~/prography
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 500


  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 200

